### ISSUE TITLE
Helm Chart Repository

### ISSUE THREAD

**Issue by sekka1** [locustio/helm-chart#2]
Hi

I want to use Locust on Kubernetes and found this repo.  However, this repo dont seem to publish the Helm Chart artifacts here so that I can just use it without cloning it out locally. For example we can publish out the artifacts to this repo like this:  https://jamiemagee.co.uk/blog/how-to-host-your-helm-chart-repository-on-github/

Is there any desire to do this?

Im also offering up my assistance to hook all this up.  With this being a public project, hosting all of this and running the github actions will all be free in this project.  If i produce the PRs, would you guys think you will accept it?

**Comment by sekka1** [comment]
@max-rocket-internet ping ping =)

**Comment by max-rocket-internet** [comment]
Hi @sekka1 

> this repo dont seem to publish the Helm Chart artifacts here so that I can just use it without cloning it out locally

I know. It was never setup and I don't think it will be. I commented saying this here: https://github.com/locustio/locust/issues/1210#issuecomment-747398642

In the mean time, I think you are better to use this chart as it's backed by a real chart repo: https://github.com/deliveryhero/helm-charts/tree/master/stable/locust

**Comment by sekka1** [comment]
@max-rocket-internet it kinda sounds like those guys were open to storing the helm chart here and it seems like you have access to this repo?  I think you will need a x.locust.io DNS record pointed to this repo for the helm chart repo.  What else is needed?

**Comment by max-rocket-internet** [comment]
> I think you will need a x.locust.io DNS record pointed to this repo for the helm chart repo. What else is needed?

More than that. A tool like https://github.com/helm/chart-releaser or https://github.com/helm/chartmuseum needs to be used, setup etc.

**Comment by sekka1** [comment]
@max-rocket-internet 
That is true.  The link to the walk through to set it up via Github actions (which is free for all open source repo) above shows how to store the helm tgz artifacts in the Github releases.  I have basically followed those instructions (really copy and pasted) and done the same for my own repo which can serve up helm charts:  https://github.com/ManagedKube/helm-charts.  The only magic outside of github is the DNS.  I am willing to give it a try for this repo and produce all the files needed and help testing if someone helps me with the DNS part.

**Comment by max-rocket-internet** [comment]
> I am willing to give it a try for this repo and produce all the files needed and help testing 

That's very kind 🎉

> if someone helps me with the DNS part

That would be @HeyHugo or @cyberw

**Comment by cyberw** [comment]
I'll email heyman , sometimes that is the best way to get a response :)

**Comment by limakzi** [comment]
@cyberw , @sekka1 We can publish Helm Chart artifacts, it means index and tarball with GitHub Pages.
Something like this: https://github.com/helm/chart-releaser-action.

**Comment by sekka1** [comment]
@limakzi What i mention in the initial comment is using this `chart-releaser-action`.  However, looking closer, it looks like the DNS is not even needed and we can just use the default github pages hostname/URL: `https://<owner>.github.io`.  I guess this is good news, we just need someone with admin access to this repo to enable the github pages.

Ill generate the stuffs in a PR.

**Comment by sekka1** [comment]
@max-rocket-internet here is a PR with the helm releaser workflow: https://github.com/locustio/helm-chart/pull/3

**Comment by heyman** [comment]
I can enable Github pages. Should it be for a separate branch or master? I can also set up the subdomain DNS if it turns our that it's still needed.

**Comment by heyman** [comment]
Ah, I just saw this in #3 now:

![image](https://user-images.githubusercontent.com/54217/110405934-af975880-8081-11eb-8fc5-2f8b074d28f6.png)

What should be the content of the `gh-pages` branch?

**Comment by sekka1** [comment]
@heyman It doesnt really matter, we are just posting artifacts to that branch.  Here is what i did before following what this person did: https://jamiemagee.co.uk/blog/how-to-host-your-helm-chart-repository-on-github/

```
git checkout --orphan gh-pages
git rm -rf .
git commit -m "Initial commit" --allow-empty
git push
```

Just an empty branch.

**Comment by heyman** [comment]
Ok! Github pages should now be up serving the `gh-pages` branch.

**Comment by max-rocket-internet** [comment]
OK I merged that PR.

We should add more CI tests/checks, we can just copy them from here more or less: https://github.com/deliveryhero/helm-charts/tree/master/.github/workflows

This will reduce the reviewing process for us and keeps the quality high.

**Comment by max-rocket-internet** [comment]
We also need a nice README 💅

I can work these points probably next week unless @sekka1 wants to to do it.

**Comment by sekka1** [comment]
@max-rocket-internet Sorry for the delayed response.  Slammed with work. Yeah, i can write the README.  Ill shoot over another PR asap.

**Comment by max-rocket-internet** [comment]
I've opened https://github.com/locustio/helm-chart/pull/4

**Comment by max-rocket-internet** [comment]
OK I've merged my PR. I'll leave the last parts up to @sekka1

I think just the instructions and repo location need to be decided and then update [here](https://github.com/locustio/helm-chart/blob/master/ci/README.md.gotmpl#L15) and main readme

**Comment by sekka1** [comment]
Ok..will review

**Comment by alexandrud** [comment]
Hi,

Any resolution on this? We're currently maintaining a helm chart in-house and it would be nice to switch to an official repo. 

Thanks!

**Comment by max-rocket-internet** [comment]
@heyman @cyberw can we make this repo private? It was never setup completely and it's confusing users 🙂

https://github.com/deliveryhero/helm-charts/issues/182#issuecomment-860337835

**Comment by cyberw** [comment]
I dont have admin, so @heyman needs to do it.

**Comment by sekka1** [comment]
Hi Everyone....sorry for dropping off of this a while back...got really busy.  

It feels like this was almost there.  Any interest in getting it over the finish line?  I have some cycles now and can take this on.

**Comment by cyberw** [comment]
I added a link to @max-rocket-internet´s version in the README. Probably people should use/contribute there instead.
